# Generated by Django 3.2.20 on 2023-10-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
