# Generated by Django 3.2.20 on 2023-10-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttachmentType', models.ImageField(upload_to='images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attachment', to='web.order')),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttachmentType', models.FileField(upload_to='files')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachment', to='web.order')),
            ],
        ),
    ]
