# Generated by Django 3.2.20 on 2023-10-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_fileattachment_imageattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='AttachmentType',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='imageattachment',
            old_name='AttachmentType',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.order'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.order'),
        ),
    ]
